name: Release

on:
  push:
    tags:
      - v*

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        token: ${{ secrets.COMMENT2BARK }}
